name: package

on: 
  - push

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: vendie
        path: ./src

