name: package

on: 
  create:
    tags:
      - v*

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: make build
      run: make build
    - name: zip artifacts
      uses: thedoctor0/zip-release@master
      with:
        filename: vendie-${{steps.vars.outputs.tag}}.zip
        type: zip
        path: vendie
    - name: create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.vars.outputs.tag}}
        repository: ${{ github.respository }}
    - name: upload release
      uses: actions/upload-release-asset
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_name: vendie-${{steps.vars.outputs.tag}}.zip
        asset_path: ./
        asset_content_type: application/zip

